package tools

const (
	CREATE_IP_PREFIX_TOOL_NAME          = "create_ipprefix"
	IPREFIX_PARAMETER_DESCRIPTION       = "The name of the IP prefix to be created. If not available, ask the user to provide the name. Do not use a random name of your choice"
	IPREFIX_LOCATION_DESCRIPTION        = "The location of the IP prefix."
	IPREFIX_PROPERTIES_DESCRIPTION      = "The properties of the IP prefix, including IP prefix rules. This should be a JSON string."
	IPREFIX_IP_DESCRIPTION              = "The IP version(s) for the IP prefix, as a JSON string array e.g., [\"ipv6\"]."
	IPREFIX_RESOURCE_GROUP_DESCRIPTION  = "The name of the resource group."
	IPREFIX_SUBSCRIPTION_ID_DESCRIPTION = "The subscription ID for the Azure account."
	DELETE_IP_PREFIX_TOOL_NAME          = "delete_ipprefix"
	PATCH_IP_PREFIX_TOOL_NAME           = "patch_ipprefix"
	GET_IP_PREFIX_TOOL_NAME             = "get_ipprefix"

	CREATE_IP_COMMUNITY_TOOL_NAME           = "create_ipcommunity"
	IPCOMMUNITY_PARAMETER_DESCRIPTION       = "The name of the IP community to be created."
	IPCOMMUNITY_LOCATION_DESCRIPTION        = "The location of the IP community."
	IPCOMMUNITY_PROPERTIES_DESCRIPTION      = "The properties of the IP community, including IP community rules. This should be a JSON string."
	IPCOMMUNITY_RESOURCE_GROUP_DESCRIPTION  = "The name of the resource group."
	IPCOMMUNITY_SUBSCRIPTION_ID_DESCRIPTION = "The subscription ID for the Azure account."
	DELETE_IP_COMMUNITY_TOOL_NAME           = "delete_ipcommunity"
	PATCH_IP_COMMUNITY_TOOL_NAME            = "patch_ipcommunity"
	GET_IP_COMMUNITY_TOOL_NAME              = "get_ipcommunity"

	CREATE_IP_EXT_COMMUNITY_TOOL_NAME          = "create_ipextcommunity"
	IPEXTCOMMUNITY_PARAMETER_DESCRIPTION       = "The name of the IP extended community to be created."
	IPEXTCOMMUNITY_LOCATION_DESCRIPTION        = "The location of the IP extended community."
	IPEXTCOMMUNITY_PROPERTIES_DESCRIPTION      = "The properties of the IP extended community, including IP extended community rules. This should be a JSON string."
	IPEXTCOMMUNITY_RESOURCE_GROUP_DESCRIPTION  = "The name of the resource group."
	IPEXTCOMMUNITY_SUBSCRIPTION_ID_DESCRIPTION = "The subscription ID for the Azure account."
	DELETE_IP_EXT_COMMUNITY_TOOL_NAME          = "delete_ipextcommunity"
	PATCH_IP_EXT_COMMUNITY_TOOL_NAME           = "patch_ipextcommunity"
	GET_IP_EXT_COMMUNITY_TOOL_NAME             = "get_ipextcommunity"

	CREATE_ROUTE_POLICY_TOOL_NAME            = "create_routepolicy"
	ROUTE_POLICY_PARAMETER_DESCRIPTION       = "The name of the Route Policy to be created."
	ROUTE_POLICY_LOCATION_DESCRIPTION        = "The location of the Route Policy."
	ROUTE_POLICY_PROPERTIES_DESCRIPTION      = "The properties of the Route Policy, including statements. This should be a JSON string."
	ROUTE_POLICY_RESOURCE_GROUP_DESCRIPTION  = "The name of the resource group."
	ROUTE_POLICY_SUBSCRIPTION_ID_DESCRIPTION = "The subscription ID for the Azure account."
	DELETE_ROUTE_POLICY_TOOL_NAME            = "delete_routepolicy"
	PATCH_ROUTE_POLICY_TOOL_NAME             = "patch_routepolicy"
	GET_ROUTE_POLICY_TOOL_NAME               = "get_routepolicy"

	CREATE_L3_ISOLATION_DOMAIN_TOOL_NAME                   = "create_l3isolationdomain"
	L3_ISOLATION_DOMAIN_PARAMETER_DESCRIPTION              = "The name of the L3 Isolation Domain to be created."
	L3_ISOLATION_DOMAIN_LOCATION_DESCRIPTION               = "The location of the L3 Isolation Domain."
	L3_ISOLATION_DOMAIN_PROPERTIES_DESCRIPTION             = "The properties of the L3 Isolation Domain. This should be a JSON string."
	L3_ISOLATION_DOMAIN_RESOURCE_GROUP_DESCRIPTION         = "The name of the resource group."
	L3_ISOLATION_DOMAIN_SUBSCRIPTION_ID_DESCRIPTION        = "The subscription ID for the Azure account."
	GET_L3_ISOLATION_DOMAIN_TOOL_NAME                      = "get_l3isolationdomain"
	GET_L3_ISOLATION_DOMAIN_ADMINISTRATIVE_STATE_TOOL_NAME = "get_l3isolationdomain_administrative_state"
	GET_L3_ISOLATION_DOMAIN_CONFIGURATION_STATE_TOOL_NAME  = "get_l3isolationdomain_configuration_state"
	DELETE_L3_ISOLATION_DOMAIN_TOOL_NAME                   = "delete_l3isolationdomain"
	PATCH_L3_ISOLATION_DOMAIN_TOOL_NAME                    = "patch_l3isolationdomain"

	ENABLE_L3_ISOLATION_DOMAIN_TOOL_NAME = "enable_l3isolationdomain"

	CREATE_INTERNAL_NETWORK_TOOL_NAME            = "create_internalnetwork"
	INTERNAL_NETWORK_PARAMETER_DESCRIPTION       = "The name of the Internal Network to be created."
	INTERNAL_NETWORK_PROPERTIES_DESCRIPTION      = "The properties of the Internal Network. This should be a JSON string."
	INTERNAL_NETWORK_RESOURCE_GROUP_DESCRIPTION  = "The name of the resource group."
	INTERNAL_NETWORK_SUBSCRIPTION_ID_DESCRIPTION = "The subscription ID for the Azure account."
	PATCH_INTERNAL_NETWORK_TOOL_NAME             = "patch_internalnetwork"
	GET_INTERNAL_NETWORK_TOOL_NAME               = "get_internalnetwork"

	DISABLE_L3_ISOLATION_DOMAIN_TOOL_NAME = "disable_l3isolationdomain"

	CREATE_L2_ISOLATION_DOMAIN_TOOL_NAME                   = "create_l2isolationdomain"
	L2_ISOLATION_DOMAIN_PARAMETER_DESCRIPTION              = "The name of the L2 Isolation Domain to be created."
	L2_ISOLATION_DOMAIN_LOCATION_DESCRIPTION               = "The location of the L2 Isolation Domain."
	L2_ISOLATION_DOMAIN_PROPERTIES_DESCRIPTION             = "The properties of the L2 Isolation Domain. This should be a JSON string."
	L2_ISOLATION_DOMAIN_RESOURCE_GROUP_DESCRIPTION         = "The name of the resource group."
	L2_ISOLATION_DOMAIN_SUBSCRIPTION_ID_DESCRIPTION        = "The subscription ID for the Azure account."
	ENABLE_L2_ISOLATION_DOMAIN_TOOL_NAME                   = "enable_l2isolationdomain"
	DISABLE_L2_ISOLATION_DOMAIN_TOOL_NAME                  = "disable_l2isolationdomain"
	GET_L2_ISOLATION_DOMAIN_TOOL_NAME                      = "get_l2isolationdomain"
	GET_L2_ISOLATION_DOMAIN_ADMINISTRATIVE_STATE_TOOL_NAME = "get_l2isolationdomain_administrative_state"
	GET_L2_ISOLATION_DOMAIN_CONFIGURATION_STATE_TOOL_NAME  = "get_l2isolationdomain_configuration_state"
	DELETE_L2_ISOLATION_DOMAIN_TOOL_NAME                   = "delete_l2isolationdomain"
	PATCH_L2_ISOLATION_DOMAIN_TOOL_NAME                    = "patch_l2isolationdomain"

	CREATE_EXTERNAL_NETWORK_TOOL_NAME            = "create_externalnetwork"
	EXTERNAL_NETWORK_PARAMETER_DESCRIPTION       = "The name of the External Network to be created."
	EXTERNAL_NETWORK_PROPERTIES_DESCRIPTION      = "The properties of the External Network. This should be a JSON string."
	EXTERNAL_NETWORK_RESOURCE_GROUP_DESCRIPTION  = "The name of the resource group."
	EXTERNAL_NETWORK_SUBSCRIPTION_ID_DESCRIPTION = "The subscription ID for the Azure account."
	PATCH_EXTERNAL_NETWORK_TOOL_NAME             = "patch_externalnetwork"
	GET_EXTERNAL_NETWORK_TOOL_NAME               = "get_externalnetwork"

	COMMIT_NETWORK_FABRIC_TOOL_NAME            = "commit_network_fabric"
	NETWORK_FABRIC_PARAMETER_DESCRIPTION       = "The name of the Network Fabric."
	NETWORK_FABRIC_RESOURCE_GROUP_DESCRIPTION  = "The name of the resource group."
	NETWORK_FABRIC_SUBSCRIPTION_ID_DESCRIPTION = "The subscription ID for the Azure account."
	GET_NETWORK_FABRIC_TOOL_NAME               = "get_network_fabric"
	LIST_DEVICES_NETWORK_FABRIC_TOOL_NAME      = "list_devices_network_fabric"

	CREATE_RESOURCE_GROUP_TOOL_NAME            = "create_resourcegroup"
	DELETE_RESOURCE_GROUP_TOOL_NAME            = "delete_resourcegroup"
	GET_RESOURCE_GROUP_TOOL_NAME               = "get_resourcegroup"
	LIST_RESOURCES_IN_RG_TOOL_NAME             = "list_resources_in_rg"
	RESOURCE_GROUP_PARAMETER_DESCRIPTION       = "The name of the Resource Group."
	RESOURCE_GROUP_LOCATION_DESCRIPTION        = "The location of the Resource Group."
	RESOURCE_GROUP_SUBSCRIPTION_ID_DESCRIPTION = "The subscription ID for the Azure account."

	GET_NETWORK_DEVICE_TOOL_NAME               = "get_network_device"
	REBOOT_NETWORK_DEVICE_TOOL_NAME            = "reboot_network_device"
	NETWORK_DEVICE_PARAMETER_DESCRIPTION       = "The name of the Network Device."
	NETWORK_DEVICE_RESOURCE_GROUP_DESCRIPTION  = "The name of the resource group."
	NETWORK_DEVICE_SUBSCRIPTION_ID_DESCRIPTION = "The subscription ID for the Azure account."

	GET_LAB_STATUS_TOOL_NAME = "get_lab_status"
)
